### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'int' and 'str'

### ISSUE THREAD

**Issue by learning2016** [cboyke1/jira_search_replace#3]
Hello
I have encountered an error. Can you tell me how to fix it?
Looking forward to your reply
-----
Traceback (most recent call last):
  File "jira_search_replace.py", line 87, in <module>
    main()
  File "jira_search_replace.py", line 15, in main
    issues=get_issues(config)
  File "jira_search_replace.py", line 27, in get_issues
    data=util.do_post(config['instance'],'search',post_data)
  File "/scripts/jira_search_replace/util.py", line 60, in do_post
    return handle_status(url,data,r)
  File "/scripts/jira_search_replace/util.py", line 85, in handle_status
    log_error(url,r.status_code,r.reason,r.text,json.dumps(data,indent=2))
  File "/scripts/jira_search_replace/util.py", line 14, in log_error
    f.write(arg+'\n')
TypeError: unsupported operand type(s) for +: 'int' and 'str'

**Comment by SiriusGale** [comment]
You should remove slash from end of url

```
[instance]
url=https://jira.domen.xx
```
